# Generated by Django 5.0.1 on 2024-01-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.TextField()),
                ('book_desc', models.TextField()),
                ('book_price', models.CharField(max_length=10)),
                ('bookimage', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
