# Generated by Django 5.0.3 on 2024-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.TextField()),
                ('author_name', models.TextField()),
                ('book_desc', models.TextField()),
                ('book_price', models.CharField(max_length=10)),
                ('bookimage', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
