# Generated by Django 5.0.3 on 2024-03-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_product_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bookimage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
