# Generated by Django 5.0.3 on 2024-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_product_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bookimage',
            field=models.ImageField(default='', upload_to='pimage/'),
        ),
    ]
