# Generated by Django 4.2.11 on 2024-03-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_alter_product_bookimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
