# Generated by Django 4.2.11 on 2024-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.TextField()),
                ('bname', models.TextField()),
                ('cvv', models.CharField(max_length=5)),
                ('Branch', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
