# Generated by Django 4.2.11 on 2024-04-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.TextField()),
                ('cardName', models.TextField()),
                ('cardNum', models.TextField()),
            ],
        ),
    ]
